development:
  adapter: redis
  url: redis://redistogo:86be7fc772c9f13aa571dc639a6aa7e6@spinyfin.redistogo.com:9123/

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: IRan_production
